# Generated by hand: add contact_number to User and copy existing phone_number values
from django.db import migrations, models


def copy_phone_to_contact(apps, schema_editor):
    User = apps.get_model('core', 'User')
    for u in User.objects.all():
        if getattr(u, 'phone_number', None) and not getattr(u, 'contact_number', None):
            u.contact_number = u.phone_number
            u.save(update_fields=['contact_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_number',
            field=models.CharField(max_length=20, null=True, blank=True),
        ),
        migrations.RunPython(copy_phone_to_contact, reverse_code=migrations.RunPython.noop),
    ]
